spring:
  application:
    name: quickcart-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  # We use ddl-auto: none and rely on schema.sql for schema initialization
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000 # 24 hours

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket: ${S3_BUCKET_NAME:quickcart1}
    region: ${AWS_REGION:us-east-1}

ai:
  groq:
    api-key: ${GROQ_API_KEY:}
  nvidia:
    api-key: ${NVIDIA_API_KEY:}
  gemini:
    api-key: ${GEMINI_API_KEY:}
  xai:
    api-key: ${XAI_API_KEY:}