spring:
  application:
    name: quickcart-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:database-1.cu3ikoym0hs3.us-east-1.rds.amazonaws.com}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:admin123}
    password: ${DB_PASSWORD:Sunny2005}
    driver-class-name: org.postgresql.Driver
  # We use ddl-auto: none and rely on schema.sql for schema initialization
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never

  mail:
    host: smtp.gmail.com
    port: 587
    username: shashankdany8712@gmail.com
    password: mhuk lhqx oqza uxwu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expirationMs: 86400000 # 24 hours

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

aws:
  s3:
    bucket: ${S3_BUCKET_NAME:quickcart-media}
    region: ${AWS_REGION:ap-south-1}

ai:
  groq:
    api-key: ${GROQ_API_KEY:}
  nvidia:
    api-key: ${NVIDIA_API_KEY:}
  gemini:
    api-key: ${GEMINI_API_KEY:}